### ISSUE TITLE
Can't pip install meza latest on Fedora 38 (and 37)

### ISSUE THREAD

**Issue by zuzzurro** [reubano/meza#47]
Hi

I'm not a python expert at all but I need installing meza on my Fedora laptop. pip install meza fails on Fedora 38 (and 37) with the following message:

```
> pip install meza
Defaulting to user installation because normal site-packages is not writeable
Collecting meza
  Using cached meza-0.46.0-py2.py3-none-any.whl (56 kB)
Collecting chardet<4.0.0,>=3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting python-slugify<2.0.0,>=1.2.5
  Using cached python-slugify-1.2.6.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.2 in /usr/lib/python3.11/site-packages (from meza) (2.8.2)
Requirement already satisfied: requests<3.0.0,>=2.18.4 in /usr/lib/python3.11/site-packages (from meza) (2.28.2)
Collecting xlrd<2.0.0,>=1.1.0
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting dbfread==2.0.4
  Using cached dbfread-2.0.4-py2.py3-none-any.whl (19 kB)
Collecting ijson<3.0.0,>=2.3
  Using cached ijson-2.6.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.6.0 in /usr/lib/python3.11/site-packages (from meza) (4.12.2)
Collecting PyYAML<6.0.0,>=4.2b1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/var/tmp/pip-build-env-fx45x08n/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Can you please advise?

**Comment by zuzzurro** [comment]
Further investigation took me here:

[https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365/2](url)

and it looks like the suggestion works for meza too. Can you still please take a look?

**Comment by jaraco** [comment]
> Further investigation took me here:
> 
> [https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365/2](url)

This link is broken. The actual link is [here](https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365/2).

This issue is implicated in https://github.com/reubano/csv2ofx/issues/111 and https://github.com/yaml/pyyaml/issues/601.
